#!/usr/bin/env ruby

require 'fileutils'
require 'shellwords'

src_home=Shellwords.escape("/Volumes/Macintosh HD - Data/Users/jeremy")
dest_home=File.expand_path("~")

top_level_dirs = %w[ 
Applications
Clients
Creative Cloud Files
Desktop
Documents
Downloads
Dropbox
Library
Movies
Music
Mylio
Pictures
Public
bin
go
problems
radar-box
repos
src
tmp
tools
]

Dir.chdir(dest_home) do
  top_level_dirs.each do |dir|
    puts "***** Syncing #{dir} *******"
    FileUtils.mkdir_p(dir)
    Dir.chdir(dir) do
      src  = File.join(src_home, dir) + "/"
      cmd  = "rsync -av --progress #{src} ."
      puts "  # PWD = #{Dir.pwd}"
      puts "  # => #{cmd}"
      system(cmd)
    end
  end
end
