#!/usr/bin/env ruby

require 'fileutils'

dest_home="/Volumes/Macintosh HD - Data/Users/jeremy"
src_home=File.expand_path("~")

#  Clients
#  Desktop
#  Documents
#  Downloads
#  Movies
#  Music
#  Mylio
#  Pictures
#  problems
top_level_dirs = %w[
  repos
  tmp
  tools
]

Dir.chdir(dest_home) do
  top_level_dirs.each do |dir|
    puts "***** Syncing #{dir} *******"
    FileUtils.mkdir_p(dir)
    Dir.chdir(dir) do
      src  = File.join(src_home, dir) + "/"
      cmd  = "rsync -av --progress #{src} ."
      puts "  # PWD = #{Dir.pwd}"
      puts "  # => #{cmd}"
      system(cmd)
    end
  end
end
